apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: handsonlab
    app.kubernetes.io/part-of: prometheus-stack
    app.kubernetes.io/version: 2.35.0
  name: handsonlabs
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 80
    targetPort: web
  - name: reloader-web
    port: 8080
    targetPort: reloader-web
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/part-of: prometheus-stack
    app.kubernetes.io/version: 2.35.0
  type: LoadBalancer