apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  type: LoadBalancer
  loadBalancerIP: "192.168.1.72"
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
