apiVersion: monitoring.coreos.com/v1 
kind: PrometheusRule
metadata:
  name: prometheus-operator-down
  namespace: monitoring
spec:
  groups:
  - name: prometheus-operator
    rules:
    - alert: PrometheusOperatorDown
      annotations:
        title: "Prometheus operator down in current."
        description: "prometheus-operator workload was down."
        summary: "[P1, Critical]: Promtheus operator has been shutdown or evicted now."
      expr: |
        ((sum(prometheus_operator_ready)) or vector(0)) == 0
      for: 30s
