apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0.30
        name: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
      - image: prom/mysqld-exporter:v0.14.0
        name: mysqld-exporter
        ports:
        - containerPort: 9104
        env:
        - name: DATA_SOURCE_NAME
          value: "root:root@(mysql:3306)/"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9104"
  labels:
    app: mysql
  name: mysql
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.1.73"
  selector:
    app: mysql
  ports:
   - name: mysql
     port: 3306
     targetPort: 3306
   - name: metrics
     port: 9104
     targetPort: 9104
