apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    monitoring: true
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: handsonlab
    app.kubernetes.io/part-of: prometheus-stack
    app.kubernetes.io/version: 2.35.0
  name: prometheus-self-scrape
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: web
  - interval: 30s
    port: reloader-web
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: handsonlab
      app.kubernetes.io/part-of: prometheus-stack
      app.kubernetes.io/version: 2.35.0