apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9104"
  labels:
    app: mysql
  name: mysql
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.1.73"
  selector:
    app: mysql
  ports:
   - name: mysql
     port: 3306
     targetPort: 3306
   - name: metrics
     port: 9104
     targetPort: 9104
  selector:
    app.kubernetes.io/component: mysql
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: mysql
    app.kubernetes.io/version: 8.0.30