apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: mysql
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: mysql
    app.kubernetes.io/version: 8.0.30
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: mysql
      app.kubernetes.io/name: mysql
      app.kubernetes.io/part-of: mysql
      app.kubernetes.io/version: 8.0.30
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mysql
        app.kubernetes.io/name: mysql
        app.kubernetes.io/part-of: mysql
        app.kubernetes.io/version: 8.0.30
    spec:
      containers:
      - image: mysql:8.0.30
        name: mysql
        resources:
          limits:
            cpu: "128m"
            memory: 300Mi
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "thisisunsafe"
      - image: prom/mysqld-exporter:v0.14.0
        name: mysqld-exporter
        env:
        - name: DATA_SOURCE_NAME
          value: "root:1234@(mysql:3306)/"
        resources:
          limits:
            cpu: "256m"
            memory: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: mysql
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: mysql
    app.kubernetes.io/version: 8.0.30
  name: mysql
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: mysql
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: mysql
    app.kubernetes.io/version: 8.0.30
  ports:
   - name: mysql
     port: 3306
     targetPort: 3306
   - name: metrics
     port: 9104
     targetPort: 9104