apiVersion: monitoring.coreos.com/v1 
kind: PrometheusRule
metadata:
  name: kubernetes-node-metric
  namespace: monitoring
spec:
  groups:
    - name: kubernetes-node-metric
      interval: 10s
      rules:
        - record: instance:node_cpu_seconds_userspace:rate2m
          expr: sum(rate(node_cpu_seconds_total{mode="user"}[2m])) by (instance)
        - record: node:node_memory:usage
          expr: |-
            100 - 100 * (
              (node_memory_MemTotal_bytes
                - node_memory_MemFree_bytes
                - node_memory_Buffers_bytes
                - node_memory_Cached_bytes
                - node_memory_SReclaimable_bytes
              )
                /
                node_memory_MemTotal_bytes
            )

