apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    release: prometheus-stack
  namespace: monitoring
  name: mysql
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: mysql
  podMetricsEndpoints:
  -  port: metrics
