
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.30
        ports:
        - name: mysql
          containerPort: 3306
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: root
        volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
      - name: mysqld-exporter
        image: prom/mysqld-exporter:v0.14.0
        ports:
        - name: metrics
          containerPort: 9104
        env:
         - name: DATA_SOURCE_NAME
           value: "root:root@(mysql:3306)/"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql

