apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: redis
    app.kubernetes.io/version: "7.0.4"
  name: redis
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.1.92"
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: redis
    app.kubernetes.io/version: "7.0.4"    