apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: redis
    app.kubernetes.io/version: 6.0
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
      app.kubernetes.io/name: redis
      app.kubernetes.io/part-of: redis
      app.kubernetes.io/version: 6.0
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: redis
      labels:
        app.kubernetes.io/component: redis
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: redis
        app.kubernetes.io/version: 6.0
    spec:
      containers:
      - image: redis:6.0
        name: redis
        resources:
          requests:
            memory: 80Mi
          limits:
            memory: 80Mi
        ports:
        - containerPort: 6379
      - image: oliver006/redis_exporter
        name: redis-exporter
        ports:
        - containerPort: 9121
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: redis
    app.kubernetes.io/version: 6.0
  name: redis
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: metrics
    port: 9121
    targetPort: 9121
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
      app.kubernetes.io/name: redis
      app.kubernetes.io/part-of: redis
      app.kubernetes.io/version: 6.0    
