apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: prometheus
    chart: prometheus-15.8.5
    heritage: Helm
  name: prometheus-alertmanager
  namespace: monitoring
