# -*- mode: ruby -*-
# vi: set ft=ruby :

docker_V = '5:26.1.3-1~ubuntu.22.04~jammy' # Docker  
ctrd_V = '1.6.31-1'   # Containerd 


# grab OS arch facts from the system.
# remove whitespace character
ARCH=`uname -m`.strip!

# arm64  > VMware Fusinon
# x86-64 > VirtualBox (else condition)
Vagrant.configure("2") do |config|
  config.vm.define "harbor" do |cfg|
    cfg.vm.box = "sysnet4admin/Ubuntu-k8s"
    if ARCH == "arm64"
      cfg.vm.provider "vmware_desktop" do |vb|
        vb.gui = true 
        vb.cpus = 1
        vb.memory = 2048
      end
    else
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "6.3.harbor(github_SysNet4Admin)"
        vb.cpus = 1
        vb.memory = 2048
        vb.customize ["modifyvm", :id, "--groups", "/Prometheus-ext-node(github_SysNet4Admin)"]
      end      
    end
    cfg.vm.host_name = "harbor"
    cfg.vm.network "private_network", ip: "192.168.1.63"
    cfg.vm.network "forwarded_port", guest: 22, host: 60063, auto_correct: true, id: "ssh"
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
    # auto dectecting OS arch and run script for each OS arch platform  
    cfg.vm.provision "shell", path: "harbor_config.sh", args: [ docker_V, ctrd_V ]
  end
end
