apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: metallb
    release: prometheus-stack
  name: metallb
  namespace: monitoring
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: monitoring
  selector:
    matchLabels:
      app: metallb