prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: 'harbor'
      metrics_path: /metrics
      static_configs:
        - targets:
            - 192.168.1.86:9090
    storageSpec: 
      volumeClaimTemplate:
      spec:
        storageClassName: "managed-nfs-storage"
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
    
  