data:
  recording_rules.yml: |
    groups:
      - name: prometheus-recording.rules
        interval: 10s
        rules:
          - record: node:node_memory:usage
            expr: |-
              100 - 100 * (
                (node_memory_MemTotal_bytes
                 - node_memory_MemFree_bytes
                 - node_memory_Buffers_bytes
                 - node_memory_Cached_bytes
                 - node_memory_SReclaimable_bytes
                )
                 /
                 node_memory_MemTotal_bytes
              )
          - record: container:memory:topk3
            expr: topk(3,sum(container_memory_working_set_bytes{pod!=""}/1024/1024) by (pod))
