data:
  alertmanager.yml: |
    global:
      resolve_timeout: 3m
    receivers:
    - name: default-receiver
    - name: pagerduty
      pagerduty_configs:
      - service_key: PD-API-KEY
    route:
      group_interval: 30s
      group_wait: 10s
      receiver: pagerduty
      repeat_interval: 2m
