prometheus:
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: "managed-nfs-storage"
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi" 
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        monitoring: true
    podMonitorSelector: 
      matchLabels:
        monitoring: true