apiVersion: monitoring.coreos.com/v1 
kind: PrometheusRule
metadata:
  name: prometheus-operator-down
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  groups:
  - name: prometheus-operator
    rules:
    - alert: PrometheusOperatorDown
      annotations:
        title: "Prometheus operator DOWN!!!"
        description: "prometheus-operator is out of service status"
        summary: "[P1, Critical]: Prometheus operator has been shutdown or evicted status unexpectedly."
      expr: |
        ((sum(prometheus_operator_ready)) or vector(0)) == 0
      for: 30s
