apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-exporter
  name: redis-exporter
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9121
    targetPort: 9121
  selector:
    app: redis-exporter
  