  # =============== #
  # prometheus Node #
  # =============== #

number_of_node = 2 # max number of node-exporters

Vagrant.configure("2") do |config|
    config.vm.define "prometheus-server" do |cfg|
      cfg.vm.box = "sysnet4admin/CentOS-k8s"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "prometheus-server"
        vb.cpus = 1
        vb.memory = 1746
        vb.customize ["modifyvm", :id, "--groups", "/prometheus"]
      end
      cfg.vm.host_name = "prometheus-server"
      cfg.vm.network "private_network", ip: "192.168.3.10"
      cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
      cfg.vm.provision "shell", path: "install_package.sh"
      cfg.vm.provision "shell", path: "get_code_from_git.sh"
    end

  #===============#
  # Node Exporter #
  #===============#

  (1..number_of_node).each do |i|
    config.vm.define "node-0#{i}" do |cfg|
      cfg.vm.box = "sysnet4admin/CentOS-k8s"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "node-0#{i}"
        vb.cpus = 1
        vb.memory = 1024
        vb.customize ["modifyvm", :id, "--groups", "/prometheus"]
      end
      cfg.vm.host_name = "node-0#{i}"
      cfg.vm.network "private_network", ip: "192.168.3.10#{i}"
      cfg.vm.network "forwarded_port", guest: 22, host: "6010#{i}", auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
      cfg.vm.provision "shell", path: "install_package.sh"
      cfg.vm.provision "shell", path: "get_code_from_git.sh"
    end
  end
end
