apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.1.85"
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis