apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: metallb
    release: prometheus
  name: metallb
  namespace: monitoring
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - interval: 30s
    port: monitoring
  selector:
    matchLabels:
      app: metallb