apiVersion: v1
kind: Service
metadata:
  name: prometheus-blackbox-exporter
  namespace: monitoring
  labels:
    app: prometheus-blackbox-exporter
spec:
  ports:
  - name: web
    port: 9115
    targetPort: web
  selector:
    app: prometheus-blackbox-exporter
    
