apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-prometheus-stack-alert
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/version: "39.9.0"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-39.9.0
    release: "prometheus-stack"
    heritage: "Helm"
spec:
  groups:
    - name: prometheus-operator
      rules:
      - alert: PrometheusOperatorDown
        annotations:
          description: prometheus-operator is out of service status
          summary: '[P1, Critical]: Prometheus operator has been shutdown or evicted status
            unexpectedly.'
          title: Prometheus operator DOWN!!!
        expr: |
          ((sum(prometheus_operator_ready)) or vector(0)) == 0
        for: 30s
