apiVersion: v1
kind: Service
metadata:
  name: prometheus-stack-prometheus-node-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
  labels:     
    app: prometheus-node-exporter
    heritage: Helm
    release: prometheus-stack
    chart: prometheus-node-exporter-3.3.1
    jobLabel: node-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9100
      targetPort: 9100
      protocol: TCP
      name: http-metrics
  selector:
    app: prometheus-node-exporter
    release: prometheus-stack
