apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-stack-prometheus-node-exporter
  namespace: monitoring
  labels:
    app: prometheus-node-exporter
    chart: prometheus-node-exporter-3.3.1
    release: "prometheus-stack"
    heritage: "Helm"
  annotations:
    {}
imagePullSecrets:
  []
