apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "server"
    app: prometheus
    release: prometheus
    chart: prometheus-15.8.5
    heritage: Helm
  name: prometheus-server
  namespace: monitoring
  